# Teamstack 고객사 .env — 03-render-configs.sh가 변수 치환 후 VPS로 업로드
# 이 파일에 들어가는 모든 값은 customer JSON + 생성된 시크릿에서 유래.

# ===== 보안 시크릿 (배포별 고유, 랜덤 생성) =====
JWT_SECRET=__JWT_SECRET__
POSTGRES_PASSWORD=__POSTGRES_PASSWORD__
BOT_PASSWORD=__BOT_PASSWORD__

# ===== LLM API 키 (고객사 별도 키) =====
OPENROUTER_API_KEY=__OPENROUTER_API_KEY__
ANTHROPIC_API_KEY=__ANTHROPIC_API_KEY__

# ===== 고객사 식별 =====
WORKSPACE_NAME=__WORKSPACE_NAME__
WORKSPACE_SLUG=__WORKSPACE_SLUG__

# ===== 3 AI 직원 정체성 =====
AI_COORDINATOR_NAME=__COORDINATOR_NAME__
AI_COORDINATOR_TITLE=__COORDINATOR_TITLE__
AI_COORDINATOR_EMAIL=__COORDINATOR_EMAIL__
AI_COORDINATOR_MODEL=__COORDINATOR_MODEL__
AI_COORDINATOR_CUSTOM_PROMPT=__COORDINATOR_CUSTOM_PROMPT__

AI_WRITER_NAME=__WRITER_NAME__
AI_WRITER_TITLE=__WRITER_TITLE__
AI_WRITER_EMAIL=__WRITER_EMAIL__
AI_WRITER_MODEL=__WRITER_MODEL__
AI_WRITER_CUSTOM_PROMPT=__WRITER_CUSTOM_PROMPT__

AI_REVIEWER_NAME=__REVIEWER_NAME__
AI_REVIEWER_TITLE=__REVIEWER_TITLE__
AI_REVIEWER_EMAIL=__REVIEWER_EMAIL__
AI_REVIEWER_MODEL=__REVIEWER_MODEL__
AI_REVIEWER_CUSTOM_PROMPT=__REVIEWER_CUSTOM_PROMPT__

# ===== 런타임 설정 =====
EXTERNAL_BOTS_ENABLED=true
AI_RANDOM_RESPONSE_CHANCE=0
AI_RESPONSE_TIMEOUT_MS=15000
NEXT_PUBLIC_API_URL=http://__VPS_IP__:__BACKEND_PORT__
